### PR TITLE
gps_common/GPSFix support

### PR DESCRIPTION
**Pull request by pjreed**
This adds support for publishing [gps_common/GPSFix](http://wiki.ros.org/gps_common) messages based on BESTPOS messages received from the NovAtel.

It also fixes an unrelated issue where the timestamp in the header of `sensor_msgs/Imu` messages was not being filled in properly.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Hi @pjreed— I'd prefer not to introduce a dependency on `gps_common`, given that there are now standard GPS messages, which this package already uses:

http://docs.ros.org/api/sensor_msgs/html/msg/NavSatFix.html

I'd be happy to merge the IMU fix though, if you'd be willing to make a separate PR for that.

**Comment by mikepurvis** [comment]
Separate PR merged as #19, thanks.

**Comment by pjreed** [comment]
I went ahead and made a separate PR for that.

Personally, I still find the GPSFix message to be far more useful than NavSatFix, as it contains a lot of information that NavSatFix doesn't; in particular the satellite statistics, track, and speed are all useful to me.  I can understand not wanting to add in another dependency, though, so I'm not sure what the best way to handle that would be.

**Comment by mikepurvis** [comment]
That is a fair statement. There's been talk at various points about better ways of handling that info in a way that would work for GPS/GLONASS/BeiDou, and I think it always basically gets stalled on the fact that the supplementary data is system-specific, and sometimes even vendor specific to a particular receiver.

We can always just publish key-value pairs or something, and that's okay for display purposes, but not much good for actually trying to make sense of it.

**Pull request closed without merging**
