### PR TITLE
Add support to serial connection

### PR DESCRIPTION
**Pull request by raucha**
Add support to serial connection.
You can test by using example_serial.launch

There is new ros params,`~/ip_address`, `~/ip_port`, `~/serial_port` and `~/serial_baud`.
Connection priority is 
`ip_address`>`serial_port`>`ip(old param)`
There is remain `~/ip` param for backward compatible.
This struct is based on these
[[REP-138] LaserScan Common Topics, Parameters, and Diagnostic Keys](http://www.ros.org/reps/rep-0138.html)
[urg_node#Parameters](http://wiki.ros.org/urg_node#Parameters)

Because I don' have ethernet enabled NovAtel sensors, I cant debug socket and I didn't edit sequence around socket .
Now I using monkey patch, that make `serial` obj compatible to `socket` object.

Sorry about my poor English.
Thank you.

### CODE REVIEW

**Comment by icolwell** [comment]
I just tested this serial connection with a new OEM7 novatel receiver and it works fine.
Anyone still maintaining this repo? I'd love to help.
I suggest we merge this PR since there are some receivers out there that do not have ethernet ports, especially newer low-cost receivers.

**Comment by mikepurvis** [comment]
Thanks for testing it out! This change looks good to me, though I would drop the `memo.md` file and revert the added whitespace.

@icolwell If you can commit to testing and maintaining this driver, I'd be delighted to give you push permissions to the repo.

**Comment by icolwell** [comment]
Hi Mike, thanks for the quick response. There are a few of us here at Waterloo that have been working on a fork of the driver. After a quick discussion we've decided I'll take take access and manage the various updates coming from our team. We've got a few nice upgrades that can definitely be merged into the official driver. We also have hardware to test on too :smile:

**Comment by JWhitleyAStuff** [comment]
AutonomouStuff is willing to do testing as well. We have also tested this PR on a NovAtel ProPak 6 (OEM638) and it works for us as well. We also support the management being transferred to Waterloo (just for the hardware availability - no offense @mikepurvis). We'll also be testing this on a SPAN IGM-S1 (serial only).

**Comment by mikepurvis** [comment]
@icolwell, @JWhitleyAStuff Both of you should now have push permissions to this repo. Please put up a PR updating the `package.xml` file with the new maintainer information. Then feel free to merge this and any other pending PRs.

Thanks for jumping in!

**Review by icolwell — CHANGES_REQUESTED** [review]
@raucha this mod seems to break the original network-based communication. Are you still interested in fixing this PR? If yes, I will post a review with things that need fixing, if not, please give me access to your repo so I can fix this PR.

**Comment by icolwell** [comment]
It's been 2 weeks so I'm going to have to assume this PR is dead. The relevant content to enable serial connections will be committed to the [serial_connection](https://github.com/ros-drivers/novatel_span_driver/tree/serial_connection) branch and continued from there.

**Comment by weisongwen** [comment]
Hi, @icolwell @mikepurvis 
Can this package support SPAN-CPT with serial connection now? Thanks a lot!

**Comment by weisongwen** [comment]
Hi, @icolwell 
Firstly, Thanks for your great work in driver of serial connection branch for SPAN-CPT.
I test the driver using my SPAN-CPT, but an issue amerged as the following picture:
29910598-15a3d556-8e5d-11e7-8442-780d1e9d1499

Do you have any idea about this issue?

I have configured the SPAN-CPT output the data in ASSIC format. was this true?Actually, SPAN-CPT could output the data in three different format: ASSIC, Binary, NMEA.

Thanks a lot.

**Comment by DRosemei** [comment]
> Hi, @icolwell
> Firstly, Thanks for your great work in driver of serial connection branch for SPAN-CPT.
> I test the driver using my SPAN-CPT, but an issue amerged as the following picture:
> 29910598-15a3d556-8e5d-11e7-8442-780d1e9d1499
> 
> Do you have any idea about this issue?
> 
> I have configured the SPAN-CPT output the data in ASSIC format. was this true?Actually, SPAN-CPT could output the data in three different format: ASSIC, Binary, NMEA.
> 
> Thanks a lot.

@weisongwen have you solved this problem? I met the same situation.

**Comment by icolwell** [comment]
@DRosemei, serial connection capability was added in this PR:
https://github.com/ros-drivers/novatel_span_driver/pull/46

Try the master branch and let me know how your testing goes.

**Pull request closed without merging**
