### PR TITLE
Fix orthometric to ellipsoidal conversion

### LINKED ISSUE #26: Orthometric to Ellipsoidal Conversion
Hello! I believe I have discovered a bug in the altitude conversion used for [producing the NavSatFix message](https://github.com/ros-drivers/novatel_span_driver/blob/master/novatel_span_driver/src/novatel_span_driver/publisher.py#L162).

[sensor_msgs/NavSatFix](http://docs.ros.org/api/sensor_msgs/html/msg/NavSatFix.html) altitude is defined relative to the WGS 84 ellipsoid, while the [BESTPOS altitude](https://www.novatel.com/assets/Documents/Manuals/OM-20000144UM.pdf#page=123) looks like it uses height above mean sea level (geoid / orthometric height).

[This application note](https://www.novatel.com/assets/Documents/Bulletins/apn006.pdf#page=2) gives the formula for conversion using the undulation value.

I can open a pull request for the [fix](https://github.com/michaelhsmart/novatel_span_driver/tree/ellipsoidal_from_orthometric) if desired.

### PR DESCRIPTION
**Pull request by michaelhsmart**
Fix #26.

Switch NavSatFix altitude assignment to use conversion from orthometric height and undulation instead of direct assignment.

### CODE REVIEW

**Comment by mikepurvis** [comment]
I'm fine with this, but let's wait to hear from the other maintainers. In particular, I'm concerned about users who may be thrown off by this change when comparing new and historical bags. So maybe this change should be part of a Kinetic/Lunar release of the driver, rather than going into Indigo? Or if you really want it in Indigo, add a parameter enabling the correct behaviour that's default-off in Indigo/Jade and default-on in Kinetic+?

Ping @ros-drivers/novatel-maintainers for other thoughts.

**Comment by michaelhsmart** [comment]
Either way works for me! We've made a lot of customizations for our specific usage of the driver and I just wanted to pass one back that looked like a genuine bug.

**Comment by icolwell** [comment]
Makes sense to me, @mikepurvis's suggestion to include it in later versions only seems appropriate. Question though: how is this driver version managed for specific ROS distros? is it currently the same code for all distros of ROS?

**Comment by jack-oquin** [comment]
It looks like the 1.0.0-0 release is on both Indigo and Jade. That's common practice for drivers, which seldom need changes from one distro to the next. It's easier to maintain with just a single master branch to consider. Releases are tagged, in case there's a need to consult the past.

**Comment by icolwell** [comment]
Should we:
1. Start branches according to ROS versions and merge this PR into kinetic and lunar only, or
2. Merge this PR into master and tag it as a new driver version (1.1.0) that only gets released for kinetic and lunar, where indigo and jade are forever stuck on version 1.0.0

Issue #28 is also calling for a kinetic release of the driver.

**Comment by mikepurvis** [comment]
It's a sleepy repo. I'm fine to just leave Indigo and Jade behind on 1.0.0.

**Pull request merged**
